# Generated by Django 6.1.1 on 2026-09-09 04:34

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('SCAN_RESULT', 'Scan Result'), ('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_file', models.FileField(upload_to=documents.models.encrypted_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patientprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
