# Generated by Django 6.1.1 on 2026-09-09 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, help_text='ID of the wearable device.', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('HEART_RATE', 'Heart Rate'), ('BLOOD_PRESSURE', 'Blood Pressure'), ('BLOOD_OXYGEN', 'Blood Oxygen'), ('TEMPERATURE', 'Temperature'), ('GLUCOSE', 'Glucose'), ('OTHER', 'Other')], max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('recorded_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
