# Generated by Django 6.1.1 on 2026-09-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='intake_notes',
            field=models.TextField(blank=True, help_text='Initial condition notes recorded at emergency intake.'),
        ),
    ]
